-- Android Restore Credentials server trust boundary (issue #1157).
--
-- WHAT THIS STORES
--
-- A restore credential is a WebAuthn-style public key the Android Credential
-- Manager created on the user's device and backs up with the device. This
-- schema holds the PUBLIC half only: the credential id, the COSE public key
-- (base64url), and a signature counter. No private key, no restored payload,
-- no OTP, and no Supabase access or refresh token is ever written here.
--
-- WHO CAN TOUCH IT
--
-- Nobody but the android-restore-credentials Edge Function (and account-delete)
-- acting as service_role, and only through the SECURITY DEFINER functions
-- below. Both tables have RLS enabled with NO policies and NO table grants, so
-- anon and authenticated can neither read nor write them, and service_role
-- cannot bypass the atomic functions with ad-hoc table writes either.
--
-- THE TWO INVARIANTS THE FUNCTIONS EXIST TO HOLD
--
--   1. A challenge is consumed exactly once. restore_consume_challenge is a
--      single conditional UPDATE: a concurrent second consumer blocks on the row
--      lock, re-evaluates `consumed_at is null` after the first commits, and
--      matches nothing. Expired, wrong-operation, cross-user, and
--      wrong-credential challenges match nothing either.
--   2. Revocation is durable and one-way. Nothing in this schema clears
--      revoked_at. restore_revoke_user is what sign-out and account deletion
--      call, and a later failure in either flow cannot make a credential
--      eligible again. It also stamps kilo.restore_revocations, and
--      registration refuses any challenge issued at or before that stamp, so a
--      registration already in flight when the user signed out cannot land a
--      fresh credential afterwards. Registration-challenge issue, registration,
--      and revocation serialize on one per-user advisory lock, which is what
--      makes that timestamp comparison a total order.
--
-- It also extends the shared security-event catalog (20260908120000) with the
-- restore events and the android-restore-credentials source. Applied
-- migrations are immutable, so the constraints and functions that carry the
-- catalog are replaced here, and scripts/security-event-monitor.test.mjs reads
-- the latest migration that defines each list.

-- ---------------------------------------------------------------------------
-- 1. Credentials
-- ---------------------------------------------------------------------------
create table if not exists kilo.restore_credentials (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  -- base64url credential id as the authenticator reported it.
  credential_id text not null unique
    check (credential_id ~ '^[A-Za-z0-9_-]+$' and length(credential_id) between 16 and 1024),
  -- base64url COSE public key. Public material only.
  public_key text not null
    check (public_key ~ '^[A-Za-z0-9_-]+$' and length(public_key) between 16 and 2048),
  sign_count bigint not null default 0 check (sign_count >= 0 and sign_count <= 4294967295),
  created_at timestamptz not null default now(),
  last_used_at timestamptz,
  revoked_at timestamptz
);

-- At most one active restore credential per user. Enrollment replaces the
-- previous one (Android keeps one restore key per app), so an old device's key
-- stops being eligible the moment a new one is registered.
create unique index if not exists restore_credentials_one_active_per_user
  on kilo.restore_credentials (user_id)
  where revoked_at is null;

alter table kilo.restore_credentials enable row level security;
revoke all on kilo.restore_credentials from public, anon, authenticated, service_role;

comment on table kilo.restore_credentials is
  'Android Restore Credentials public keys (issue #1157). Public material only. RLS deny-all with no table grants; reached only through the kilo.restore_* security-definer functions.';

-- ---------------------------------------------------------------------------
-- 2. Challenges
-- ---------------------------------------------------------------------------
create table if not exists kilo.restore_challenges (
  id bigint generated always as identity primary key,
  -- base64url of 32 random bytes, generated by the Edge Function.
  challenge text not null unique
    check (challenge ~ '^[A-Za-z0-9_-]{43,128}$'),
  operation text not null check (operation in ('registration', 'assertion')),
  -- Registration challenges are bound to the enrolling user.
  user_id uuid references auth.users (id) on delete cascade,
  -- Assertion challenges are bound to the credential id the caller asked
  -- about. Deliberately NOT a foreign key: restore-options must issue an
  -- identical challenge for an unknown credential id, or its response would
  -- reveal which credential ids exist.
  credential_id text check (credential_id ~ '^[A-Za-z0-9_-]+$' and length(credential_id) between 16 and 1024),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  consumed_at timestamptz,
  constraint restore_challenges_binding check (
    (operation = 'registration' and user_id is not null and credential_id is null)
    or (operation = 'assertion' and credential_id is not null and user_id is null)
  ),
  constraint restore_challenges_expiry check (expires_at > created_at)
);

create index if not exists restore_challenges_expires_idx
  on kilo.restore_challenges (expires_at);
create index if not exists restore_challenges_user_idx
  on kilo.restore_challenges (user_id) where user_id is not null;
create index if not exists restore_challenges_credential_idx
  on kilo.restore_challenges (credential_id) where credential_id is not null;

alter table kilo.restore_challenges enable row level security;
revoke all on kilo.restore_challenges from public, anon, authenticated, service_role;

comment on table kilo.restore_challenges is
  'One-time Android Restore Credentials challenges (issue #1157). Consumed atomically by kilo.restore_consume_challenge. RLS deny-all with no table grants.';

-- ---------------------------------------------------------------------------
-- 2b. Revocation marker
-- ---------------------------------------------------------------------------
--
-- The last time each user's restore credentials were revoked. A registration
-- whose challenge was issued at or before this instant is refused even if its
-- challenge was already consumed, because that registration started before
-- the user signed out (or before account deletion began).
create table if not exists kilo.restore_revocations (
  user_id uuid primary key references auth.users (id) on delete cascade,
  revoked_at timestamptz not null
);

alter table kilo.restore_revocations enable row level security;
revoke all on kilo.restore_revocations from public, anon, authenticated, service_role;

comment on table kilo.restore_revocations is
  'Per-user Android Restore Credentials revocation stamp (issue #1157). Registrations whose challenge predates it are refused. RLS deny-all with no table grants.';

-- One lock key per user for registration-challenge issue, registration, and
-- revocation. Transaction-scoped, so it is released at commit.
create or replace function kilo.restore_lock_user(p_user_id uuid)
returns void
language sql
security definer
set search_path = ''
as $$
  select pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext('restore_user:' || p_user_id::text))
$$;

revoke all on function kilo.restore_lock_user(uuid) from public, anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 3. Functions (service_role only)
-- ---------------------------------------------------------------------------

-- Stores a new challenge. Also prunes challenges that expired over an hour ago,
-- so the table stays bounded without a scheduled job; the unauthenticated
-- caller is rate-limited upstream, which bounds the insert rate.
create or replace function kilo.restore_issue_challenge(
  p_operation text,
  p_challenge text,
  p_user_id uuid,
  p_credential_id text,
  p_ttl_seconds integer
)
returns timestamptz
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_expires timestamptz;
begin
  if p_ttl_seconds is null or p_ttl_seconds < 30 or p_ttl_seconds > 600 then
    raise exception 'restore challenge ttl out of range';
  end if;

  delete from kilo.restore_challenges c
  where c.expires_at < now() - interval '1 hour';

  -- Registration challenges are ordered against revocation under the user's
  -- lock, with a wall-clock issue time so the comparison in
  -- restore_register_credential is exact.
  if p_operation = 'registration' and p_user_id is not null then
    perform kilo.restore_lock_user(p_user_id);
  end if;

  v_expires := pg_catalog.clock_timestamp() + make_interval(secs => p_ttl_seconds);

  insert into kilo.restore_challenges (challenge, operation, user_id, credential_id, created_at, expires_at)
  values (p_challenge, p_operation, p_user_id, p_credential_id, pg_catalog.clock_timestamp(), v_expires);

  return v_expires;
end;
$$;

-- Consumes a challenge exactly once. Returns true only for the single caller
-- that flips consumed_at on an unexpired challenge whose operation and binding
-- match. Everything else -- replay, expiry, wrong operation, another user's
-- registration challenge, another credential's assertion challenge -- is false.
create or replace function kilo.restore_consume_challenge(
  p_operation text,
  p_challenge text,
  p_user_id uuid,
  p_credential_id text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id bigint;
begin
  update kilo.restore_challenges c
     set consumed_at = now()
   where c.challenge = p_challenge
     and c.operation = p_operation
     and c.consumed_at is null
     and c.expires_at > now()
     and (
       (p_operation = 'registration' and c.user_id = p_user_id)
       or (p_operation = 'assertion' and c.credential_id = p_credential_id)
     )
  returning c.id into v_id;

  return v_id is not null;
end;
$$;

-- Registers a verified credential for a user, replacing any active one. One
-- statement block, so a failure (for example a credential id that is already
-- registered) rolls back the revocation of the previous credential too: the
-- user is never left with neither.
--
-- p_challenge is the registration challenge the caller consumed before
-- verifying. Returns null -- refusing the registration -- when that challenge
-- is not this user's consumed registration challenge, or when the user's
-- credentials were revoked at or after the challenge was issued.
create or replace function kilo.restore_register_credential(
  p_user_id uuid,
  p_challenge text,
  p_credential_id text,
  p_public_key text,
  p_sign_count bigint
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id uuid;
  v_issued timestamptz;
  v_revoked timestamptz;
begin
  if not exists (select 1 from auth.users u where u.id = p_user_id) then
    raise exception 'restore credential owner does not exist';
  end if;

  perform kilo.restore_lock_user(p_user_id);

  select c.created_at into v_issued
  from kilo.restore_challenges c
  where c.challenge = p_challenge
    and c.operation = 'registration'
    and c.user_id = p_user_id
    and c.consumed_at is not null;
  if v_issued is null then
    return null;
  end if;

  select r.revoked_at into v_revoked
  from kilo.restore_revocations r
  where r.user_id = p_user_id;
  if v_revoked is not null and v_revoked >= v_issued then
    return null;
  end if;

  update kilo.restore_credentials rc
     set revoked_at = now()
   where rc.user_id = p_user_id
     and rc.revoked_at is null;

  insert into kilo.restore_credentials (user_id, credential_id, public_key, sign_count)
  values (p_user_id, p_credential_id, p_public_key, coalesce(p_sign_count, 0))
  returning id into v_id;

  return v_id;
end;
$$;

-- Returns the ACTIVE credential for an id, or no row. A revoked credential and
-- an unknown one are indistinguishable to the caller.
create or replace function kilo.restore_lookup_credential(p_credential_id text)
returns table (user_id uuid, public_key text, sign_count bigint)
language sql
stable
security definer
set search_path = ''
as $$
  select rc.user_id, rc.public_key, rc.sign_count
  from kilo.restore_credentials rc
  where rc.credential_id = p_credential_id
    and rc.revoked_at is null
$$;

-- Records a successful assertion immediately before a session is issued.
-- Returns false if the credential was revoked (or re-bound) after it was looked
-- up, which closes the race with a concurrent sign-out or account deletion.
create or replace function kilo.restore_record_use(
  p_credential_id text,
  p_user_id uuid,
  p_sign_count bigint
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id uuid;
begin
  update kilo.restore_credentials rc
     set last_used_at = now(),
         sign_count = greatest(rc.sign_count, coalesce(p_sign_count, 0))
   where rc.credential_id = p_credential_id
     and rc.user_id = p_user_id
     and rc.revoked_at is null
  returning rc.id into v_id;

  return v_id is not null;
end;
$$;

-- Revokes every active credential for a user and burns their outstanding
-- challenges. Called by sign-out (the revoke route) and FIRST by account-delete.
-- Idempotent; returns the number of credentials it revoked.
create or replace function kilo.restore_revoke_user(p_user_id uuid)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_revoked integer;
begin
  perform kilo.restore_lock_user(p_user_id);

  -- Stamped under the lock, so every registration challenge issued before this
  -- instant is refused by restore_register_credential, including one that was
  -- already consumed by a registration still in flight.
  insert into kilo.restore_revocations (user_id, revoked_at)
  values (p_user_id, pg_catalog.clock_timestamp())
  on conflict (user_id) do update set revoked_at = excluded.revoked_at;

  update kilo.restore_challenges c
     set consumed_at = now()
   where c.consumed_at is null
     and (
       c.user_id = p_user_id
       or c.credential_id in (
         select rc.credential_id from kilo.restore_credentials rc where rc.user_id = p_user_id
       )
     );

  update kilo.restore_credentials rc
     set revoked_at = now()
   where rc.user_id = p_user_id
     and rc.revoked_at is null;
  get diagnostics v_revoked = row_count;

  return v_revoked;
end;
$$;

revoke all on function kilo.restore_issue_challenge(text, text, uuid, text, integer) from public, anon, authenticated;
revoke all on function kilo.restore_consume_challenge(text, text, uuid, text) from public, anon, authenticated;
revoke all on function kilo.restore_register_credential(uuid, text, text, text, bigint) from public, anon, authenticated;
revoke all on function kilo.restore_lookup_credential(text) from public, anon, authenticated;
revoke all on function kilo.restore_record_use(text, uuid, bigint) from public, anon, authenticated;
revoke all on function kilo.restore_revoke_user(uuid) from public, anon, authenticated;

grant execute on function kilo.restore_issue_challenge(text, text, uuid, text, integer) to service_role;
grant execute on function kilo.restore_consume_challenge(text, text, uuid, text) to service_role;
grant execute on function kilo.restore_register_credential(uuid, text, text, text, bigint) to service_role;
grant execute on function kilo.restore_lookup_credential(text) to service_role;
grant execute on function kilo.restore_record_use(text, uuid, bigint) to service_role;
grant execute on function kilo.restore_revoke_user(uuid) to service_role;

-- ---------------------------------------------------------------------------
-- 4. Security-event catalog extension
-- ---------------------------------------------------------------------------
--
-- Same four-layer contract as 20260908120000: the CHECK constraints, the
-- severity map, the context reason allow-list, and record_security_event's
-- source check all move together, and security-event.ts mirrors them.

alter table kilo.security_events drop constraint if exists security_events_event_name_check;
alter table kilo.security_events add constraint security_events_event_name_check
  check (event_name in (
    'auth.token_missing',
    'auth.token_rejected',
    'authz.denied',
    'ratelimit.ip_blocked',
    'ratelimit.user_blocked',
    'ratelimit.unavailable',
    'account.export_succeeded',
    'account.delete_succeeded',
    'account.delete_failed',
    'health.purge_succeeded',
    'health.purge_failed',
    'server.error',
    'restore.enrolled',
    'restore.assertion_accepted',
    'restore.assertion_rejected',
    'restore.session_issued',
    'restore.session_failed',
    'restore.revoked'
  ));

alter table kilo.security_events drop constraint if exists security_events_source_check;
alter table kilo.security_events add constraint security_events_source_check
  check (source in (
    'account-export',
    'account-delete',
    'health-data-delete',
    'android-restore-credentials'
  ));

create or replace function kilo.security_event_severity(p_event_name text)
returns text
language sql
immutable
set search_path = ''
as $$
  select case p_event_name
    when 'ratelimit.unavailable' then 'critical'
    when 'authz.denied' then 'critical'

    when 'auth.token_rejected' then 'warning'
    when 'ratelimit.ip_blocked' then 'warning'
    when 'ratelimit.user_blocked' then 'warning'
    when 'account.delete_failed' then 'warning'
    when 'health.purge_failed' then 'warning'
    when 'server.error' then 'warning'
    -- A restore assertion that failed verification. One is a stale device; a
    -- rate of them across many origins is someone trying keys.
    when 'restore.assertion_rejected' then 'warning'
    -- A verified assertion that still produced no session: the account became
    -- ineligible or GoTrue refused the exchange.
    when 'restore.session_failed' then 'warning'

    when 'auth.token_missing' then 'info'
    when 'account.export_succeeded' then 'info'
    when 'account.delete_succeeded' then 'info'
    when 'health.purge_succeeded' then 'info'
    when 'restore.enrolled' then 'info'
    when 'restore.assertion_accepted' then 'info'
    when 'restore.session_issued' then 'info'
    when 'restore.revoked' then 'info'
    else null
  end
$$;

revoke all on function kilo.security_event_severity(text) from public;

create or replace function kilo.sanitize_security_event_context(p_context jsonb)
returns jsonb
language plpgsql
immutable
set search_path = ''
as $$
declare
  v_out jsonb := '{}'::jsonb;
  v_status numeric;
  v_count numeric;
  v_text text;
begin
  if p_context is null or jsonb_typeof(p_context) <> 'object' then
    return v_out;
  end if;

  if jsonb_typeof(p_context -> 'status') = 'number' then
    v_status := (p_context -> 'status')::numeric;
    if v_status >= 100 and v_status <= 599 and v_status = trunc(v_status) then
      v_out := v_out || jsonb_build_object('status', v_status::int);
    end if;
  end if;

  v_text := p_context ->> 'reason';
  if v_text in (
    'missing_token',
    'invalid_token',
    'ip_throttle',
    'user_throttle',
    'limiter_unavailable',
    'evidence_key_missing',
    'db_error',
    'incomplete',
    'subject_mismatch',
    'unknown',
    'malformed',
    'config_missing',
    'challenge_invalid',
    'credential_inactive',
    'verification_failed',
    'user_ineligible',
    'issuer_error'
  ) then
    v_out := v_out || jsonb_build_object('reason', v_text);
  end if;

  v_text := p_context ->> 'code';
  if v_text is not null and v_text ~ '^[A-Za-z0-9_.:-]{1,40}$' then
    v_out := v_out || jsonb_build_object('code', v_text);
  end if;

  v_text := p_context ->> 'request_id';
  if v_text is not null and v_text ~ '^[A-Za-z0-9_-]{1,64}$' then
    v_out := v_out || jsonb_build_object('request_id', v_text);
  end if;

  if jsonb_typeof(p_context -> 'count') = 'number' then
    v_count := (p_context -> 'count')::numeric;
    if v_count >= 0 and v_count <= 1000000 and v_count = trunc(v_count) then
      v_out := v_out || jsonb_build_object('count', v_count::bigint);
    end if;
  end if;

  return v_out;
end;
$$;

revoke all on function kilo.sanitize_security_event_context(jsonb) from public;

create or replace function kilo.record_security_event(
  p_event_name text,
  p_source text,
  p_outcome text,
  p_subject_type text,
  p_subject text,
  p_context jsonb
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_severity text;
  v_digest text;
  v_recent integer;
begin
  v_severity := kilo.security_event_severity(p_event_name);
  if v_severity is null then
    raise exception 'unknown security event name';
  end if;

  if p_source is null or p_source not in ('account-export', 'account-delete', 'health-data-delete', 'android-restore-credentials') then
    raise exception 'unknown security event source';
  end if;

  if p_outcome is null or p_outcome not in ('allowed', 'denied', 'succeeded', 'failed') then
    raise exception 'unknown security event outcome';
  end if;

  if p_subject_type is null or p_subject_type not in ('user', 'ip', 'none') then
    raise exception 'unknown security event subject type';
  end if;

  if p_subject_type = 'none' then
    v_digest := null;
  else
    if p_subject is null or length(trim(p_subject)) = 0 then
      raise exception 'security event subject is required for subject type %', p_subject_type;
    end if;
    v_digest := kilo.security_event_subject_digest(trim(p_subject));
  end if;

  -- Ingest cap, serialized per event name. Unchanged from 20260908120000; see
  -- that migration for why the advisory lock is what makes the bound hold.
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtext('security_event:' || p_event_name)
  );

  select count(*) into v_recent
  from kilo.security_events e
  where e.event_name = p_event_name
    and e.occurred_at > now() - interval '1 minute';

  if v_recent >= 60 then
    return false;
  end if;

  insert into kilo.security_events (
    event_name, source, severity, outcome, subject_type, subject_digest, context
  ) values (
    p_event_name,
    p_source,
    v_severity,
    p_outcome,
    p_subject_type,
    v_digest,
    kilo.sanitize_security_event_context(p_context)
  );

  return true;
end;
$$;

revoke all on function kilo.record_security_event(text, text, text, text, text, jsonb) from public, anon, authenticated;
grant execute on function kilo.record_security_event(text, text, text, text, text, jsonb) to service_role;
